import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Video slider",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ko">
      <body>
        {children}
      </body>
    </html>
  );
}
